language: python
python:
  - "3.5"
  - "3.4"
  - "2.7"

# command to run tests
script:
  - if [[ ${TRAVIS_PYTHON_VERSION} == '2.7' ]]; then py.test -v -m selfinstall; fi
  - if [[ ${TRAVIS_PYTHON_VERSION} != '2.7' ]]; then py.test -v; fi

# Ensure dependencies are installed
install: pip install requests testpath
